# Generated by Django 5.2.1 on 2026-04-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Руководитель'), ('hr', 'HR-специалист'), ('admin', 'Администратор')], default='employee', max_length=20),
        ),
    ]
