# Generated by Django 5.2.1 on 2026-02-15 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('vacation', 'Отпуск'), ('business_trip', 'Командировка')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('in_approval', 'На согласовании'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('role', models.CharField(choices=[('manager', 'Руководитель'), ('hr', 'HR-специалист')], max_length=20)),
                ('decision', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.request')),
            ],
            options={
                'ordering': ['request', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('vacation', 'Отпуск'), ('business_trip', 'Командировка')], max_length=20)),
                ('step_number', models.IntegerField()),
                ('role', models.CharField(choices=[('manager', 'Руководитель'), ('hr', 'HR-специалист')], max_length=20)),
                ('sla_days', models.IntegerField()),
            ],
            options={
                'unique_together': {('request_type', 'step_number')},
            },
        ),
    ]
