# Generated by Django 5.2.1 on 2026-04-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_request_comment_request_end_date_request_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('pending', 'На рассмотрении'), ('in_approval', 'На согласовании'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='draft', max_length=20),
        ),
    ]
