# Generated by Django 5.2.1 on 2026-04-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='rejection_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
