# Generated by Django 5.2.1 on 2026-05-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_request_rejection_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
